### ISSUE TITLE
Console error Uncaught (in promise) Error: There is already an encoder stored which handles exactly the same mime types.     at Worker.<anonymous> (module.ts:49:1)

### ISSUE THREAD

**Issue by gwhizoftv** [DeltaCircuit/react-media-recorder#105] opened 2022-07-18 17:32 UTC
Hi, Thank you for making this package! It gives  this error when using the basic wrapper code:
```
import './App.css';
import { ReactMediaRecorder } from 'react-media-recorder'
 
function App() {
 return (
    <ReactMediaRecorder
       video
       render={({ status, startRecording, stopRecording, mediaBlobUrl }) => (
         <div>
          <p>{status}\</p>
          <button onClick={startRecording}>Start Recording</button>
          <button onClick={stopRecording}>Stop Recording</button>
          <video src={mediaBlobUrl} controls autoPlay loop />
         </div>
        )}
     />
   );
 }
 
 export default App;
``` 

My environment is:

- Macos Monterey, 
- Chrome 103, 
- the project was created using npx create-react-app, 
- the package was installed with npm
- dependencies from Package.json:
```
"dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-media-recorder": "^1.6.6",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4"`
 ```

As you can see in the above code, I'm not setting any of the options available, especially the mimetype.

**Comment by HumbleDev-1119** [comment] 2022-07-25 01:57
I'm also facing same issue.
![record_issue](https://user-images.githubusercontent.com/32957829/180678521-8ae64474-f39a-4660-adb8-b324886e311f.png)

**Comment by jaeyoungheo8697** [comment] 2022-07-26 06:25
<img width="482" alt="image" src="https://user-images.githubusercontent.com/74174743/180937968-1e4e9cea-8119-4cdf-80b7-a2ef6433c71c.png">
same issue.

**Comment by merttyilmaz** [comment] 2022-07-26 09:03
I'm also having this issue. The issue happens when I'm navigating between different pages in my application. I'm using hooks.

**Comment by pavlonsp** [comment] 2022-08-01 09:39
Hi, me too have this issue. The issue happens when I'm navigating between different pages in my application. I'm using hooks.

**Comment by charlesjavelona** [comment] 2022-08-01 15:43
Same here:

Component page: 
```CreateLivestreampage.js
  const RecordEventCreation = dynamic(
    () => import("../../components/Record/RecordEventCreation")
  );
```

```RecordEventCreation.js
  import { useReactMediaRecorder, StatusMessages} from 'react-media-recorder';
```

**Comment by freeday** [comment] 2022-08-02 17:09
i have this error when i use react-router and use history.push inside onRedirectCommand

**Comment by JackCompass** [comment] 2022-08-08 07:33
Hello everyone, I was facing the same issue. The most straightforward way to solve this is to remove the strict mode from your project.

**Comment by jessejamesrich** [comment] 2022-08-22 21:04
I have the same issue when using react-router. Removing strict does not work for those in CRA. At the moment, I imagine something is going on with a re-rendering.

**Comment by drummerjolev** [comment] 2022-09-28 17:19
Having the same issue as I'm re-using the hook multiple times on the same page. I don't want to drop strict mode and it doesn't solve the issue anyway for CRA, as @jessejamesrich pointed out.

I tried switching `blobPropertyBag` to `{type: 'audio/mp3'}` (from the default `{type: 'audio/wav'}`), though that had the same error. @0x006F would you be open to make the logic running in the `useEffect` optional? See https://github.com/0x006F/react-media-recorder/issues/105#issuecomment-1195057490

**Comment by jessejamesrich** [comment] 2022-09-28 17:35
I found this issue returned just recently as well. So I will be back to look at it here.

**Comment by tochukwu19** [comment] 2022-10-11 20:32
I too am experiencing this issue

**Comment by kalib-code** [comment] 2022-10-13 09:24
Same issue though mine I'm calling it inside a modal.

**Comment by bashtblrkin** [comment] 2022-11-15 08:56
Hi, me too have this issue. I'm using hooks. The issue happens when I'm navigating between different pages in my application and reload page.

**Comment by treyholt** [comment] 2022-11-16 01:05
Same issue here as well. Called in a modal, using hooks (also Next)

**Comment by treyholt** [comment] 2022-11-16 01:33
The encoder error goes away for me downgrading to 1.6.5

**Comment by 0x006F** [comment] 2022-11-19 11:27
Hey everyone, 

I'm sorry, I've been away for a while and couldn't keep up on this. I really appreciate everyone's involvement in this, and of course your patience. 

Read through the comments and related issues, and it feels like it's specific to NextJS or am I plain wrong? (or SSR in general). 

If anyone has an open PR to solve, this, I'd really appreciate it. It'd take another week or two for me to settle down everything. 

Once again, I appreciate everyone's patience. Thanks!

**Comment by Faridmurzone** [comment] 2022-11-27 22:43
The same thing happened to me today. As some comments previously said removing the 'strict mode' can make the error disappear. 
The problem occurs because the useEffect on line 84 (https://github.com/0x006F/react-media-recorder/blob/master/src/index.ts#L84) register the wav encoders every time the component is mounted. 
On some occasions (it can be with strict mode but also for other reasons such as re-rendering the parent component in the tree) the render ocurs 2 or more times and this causes an error.
The problem is that it's not enough to interrupt the execution of the function in the unmount behavior, because under the hood it is registering the encoders with workers. I didn't find a simple way to call the worker and interrupt it. So i just wrapped the useEffect function in a try catch to work bypassing that problem. Also for those people who doesn't need audio maybe you can avoid to register the encoders. Here is my code with both things (try catch wrapper and audio verification before register encoders)


```
  useEffect(() => {
    const setup = async () => {
      try {
        audio && await register(await connect());
      } catch (error) {
        console.error(error)
      }
    };
    setup();
  }, []);
```

**Comment by MarioArriaga92** [comment] 2022-12-02 20:26
Any update on this? It'd be nice to get a patch version out hehe

**Comment by pedrosimao** [comment] 2023-01-08 22:02
@Faridmurzone , thanks a lot for this, it fixed for me

**Comment by gameveloster** [comment] 2023-02-02 03:52
Anyone mind opening a PR to patch this? Thanks

**Comment by AliverdiSultanli** [comment] 2023-02-10 15:35
Change version to 1.4.0

**Comment by christopher-kapic** [comment] 2023-02-21 17:52
It seems that there might be a conflict with the npm versioning.
Note: I'm not terribly familiar with publishing npm packages, so forgive me if I have this wrong.
On npmjs.com, the [package](https://www.npmjs.com/package/react-media-recorder) is on version 1.6.6, but on [Github](https://github.com/0x006F/react-media-recorder), the package is on version 1.4.0. It also looks like there is a different owner on npmjs.com, or @0x006F changed their username.

**Comment by marefati110** [comment] 2023-03-18 16:49
I have forked this project and I am doing the bug fixes, you can use this package

https://www.npmjs.com/package/react-media-recorder-2

**Comment by holyMolyTolli** [comment] 2023-04-10 22:18
> I have forked this project and I am doing the bug fixes, you can use this package
> 
> https://www.npmjs.com/package/react-media-recorder-2

That works like a charm :) <2

**Comment by AtleMichaelSelberg** [comment] 2023-04-19 00:42
I'm also having this issue

**Comment by maktoobgar** [comment] 2023-05-10 12:56
> I have forked this project and I am doing the bug fixes, you can use this package
> 
> https://www.npmjs.com/package/react-media-recorder-2

That's why you're the goat. ❤️

**Comment by Marconoyet** [comment] 2023-07-16 16:35
How to download video from it as mp4 react media recorder

**Comment by TomerBu** [comment] 2023-07-26 13:44
> How to download video from it as mp4 react media recorder

```
  <a
        href={mediaBlobUrl}
        download
      >
        Download
      </a>
```

**Comment by ijas-aslam** [comment] 2023-07-29 17:17
https://www.npmjs.com/package/react-media-recorder-2
This is working well 😍

**Comment by abhijeetvinkare** [comment] 2023-08-29 02:52
@treyholt The encoder error went away for me on NextJS by downgrading to 1.6.5
npm i react-media-recorder@1.6.5 ... this solution worked, also worked for me in ReactJS ... Thanks!

**Comment by fkadeal** [comment] 2023-09-06 06:26
> The encoder error went away for me on NextJS by downgrading to 1.6.5 `npm i react-media-recorder@1.6.5`
https://github.com/DeltaCircuit/react-media-recorder/issues/105#issuecomment-1316148883
thanks this work perfectly

**Comment by jasondainter** [comment] 2023-09-28 13:58
Had the same issue was driving me nuts. 

Downgrade to 1.6.5 fixes it. 

https://www.npmjs.com/package/react-media-recorder-2 also works.

Wouldnt it make sense to update the original react-media-recorder with a fix? Is anyone still maintaining that or is react-media-recorder-2 where its at now?

**Comment by JonhZono** [comment] 2023-11-05 14:45
@marefati110 it worked for me as well, you are a goat bro

**Comment by amitthk** [comment] 2024-05-21 06:28
Same issue still.

**Comment by tk-powder** [comment] 2024-08-16 06:58
Hello, @DeltaCircuit. I love the library and seems to have consistent updats. By any chance, will this become a higher priority and resolve any time soon? This has been opened for more than a year.

**Comment by jasondainter** [comment] 2024-08-20 10:54
@AshishDhama @DeltaCircuit any chance either of you could push a fix for this. Works fine in https://www.npmjs.com/package/react-media-recorder-2 but would be nice to use the original package if this is now going to be maintained. 
I'm using this in a project at the moment, somewhat of a noob programmer but happy to put time/resources in where I can if this issue gets addressed!

**Comment by AshishDhama** [comment] 2024-08-21 16:41
@jasondainter Let me take a look on this weekend. Mean while if you have a fix, please feel free to raise a Pr or if Pr is already up with the fix please share.

**Comment by AshishDhama** [comment] 2024-08-28 08:14
@christopher-kapic Thanks for the PR. I went through it, @marefati110 have removed selfBrowserSurface from his package. Although it was experimental but do have potential of breaking it for some people. So I think I can't merge it in current state. I will pick changes required to fix this error maybe in new PR. But assure you all these changes will be done in couple of days.

**Comment by AshishDhama** [comment] 2024-09-02 04:32
I have merged https://github.com/DeltaCircuit/react-media-recorder/pull/142, Please try running master. I will collaborate with @DeltaCircuit to publish this to npm.

**Comment by tk-powder** [comment] 2024-09-02 18:23
This is a great news. Thanks @AshishDhama

**Comment by jasondainter** [comment] 2024-09-02 19:08
Great to see this being developed again, nice work!

**Comment by DeltaCircuit** [comment] 2024-09-03 14:52
Apologies for the delay. The latest master have been published. V1.7.1

**Comment by khera** [comment] 2024-09-09 17:38
> Apologies for the delay. The latest master have been published. V1.7.1

Awesome. Cleared up the problem for me using Remix.

**Closed** 2024-09-10 03:10 UTC
